version: '2'
services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    networks:
    - qgis
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./map.html:/usr/share/nginx/html/index.html:ro
    depends_on:
    - qgis-exec
  qgis-exec:
    image: qgis-2.14.22
    networks:
    - qgis
    volumes:
    - /data:/data:ro
    environment:
    - QGIS_DEBUG=1
    - QGIS_LOG_FILE=/tmp/qgis.log
    - QGIS_SERVER_LOG_LEVEL=0
    - QGIS_SERVER_LOG_FILE=/tmp/qgisserver.log

networks:
  qgis: {}
