version: '2'
services:
  nginx:
    image: nginx:1.13
    ports:
    - 8080:80
    networks:
    - qgis
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./map.html:/usr/share/nginx/html/index.html:ro
    depends_on:
    - qgis-exec
  qgis-exec:
    image: qgis-exec:2.18
    networks:
    - qgis
    volumes:
    - ./data:/data:ro
    environment:
    - QGIS_PROJECT_FILE=/data/osm.qgs
networks:
  qgis: {}
